version: "3"
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: "messanger_project"
      MYSQL_PASSWORD: ensasha2002
      MYSQL_ROOT_PASSWORD: ensasha2002
    command: mysqld --disable-ssl --sql_mode=""
